### PR TITLE
Modernize Python 2 code to get ready for Python 3

### PR DESCRIPTION
**Pull request by cclauss**
$ __futurize --stage1 -w .__  # http://python-future.org/futurize_cheatsheet.html

Minimal, safe changes required to make this code syntax compatible with both Python 2 and Python 3. More changes will be required to complete the port to Python 3 but this should provide a solid start in that process without breaking backward compatibility with legacy Python.

### CODE REVIEW

**Comment by cclauss** [comment]
@v1993 _Anyone_ can review a pull request by:
1. Click __Files changed__ just below the title of the pull request
2. Click the __Review changes__ button
3. Click the __Approve__ button
4. Click the __Submit review__ button

Instead of a 👍 on a pull request, it will help the maintainer (danmacnish) if you give a _positive review_.  That way, it is clear that you have looked through these changes and approve them as both useful and safe.

**Comment by v1993** [comment]
@cclauss I can't say anything about "safe" — I don't know python, but they seem useful. What about included modules?

**Comment by cclauss** [comment]
I understand the README message that _*Unfortunately python 2.7 is required because the correct python 3 wheels are not available for both the pi and desktop._ but it is still useful to ensure that the code of this repo is compatible so that when those wheels are available, we can easily flip the switch away from legacy Python.

**Comment by cclauss** [comment]
Where is "__pi__" installed?  I see that [desktop not installed on Raspberry Pi](https://github.com/danmacnish/cartoonify#desktop-installation-only-tested-on-osx-and-linux) but I was unable to find "__pi__" in the Dockerfile or any of the requirements.txt files.  Is it https://pypi.org/project/pi or some other package?

**Pull request closed without merging**
